{% set name = "sqlmodel" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlmodel-{{ version }}.tar.gz
  sha256: 2652b2202425d56d96ea46af096b2c4d7d4ff8519264f8b4d042947e0580ea8d

build:
  noarch: python
  script:
    # Unfortunately sqlmodel relies on a custom plugin called "poetry-version-plugin"
    # which relies on the development version of poetry, which is annoying to install
    # on conda-forge. But why install some weird plugin when we can just use a simple
    # Bash hack? ;)

    # Verify that the version is correctly set in __init__.py
    - grep __version__ sqlmodel/__init__.py | grep {{ version }}
    # Replace the version number in the pyproject.toml with the one we extracted
    - sed -i "s/version = \"0\"/version = \"{{ version }}\"/" pyproject.toml
    # Install
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7,<4.0
    - sqlalchemy >=2.0.0,<2.1.0
    - pydantic >=1.9.0,<2.0.0

test:
  imports:
    - sqlmodel
  commands:
    - pip check
    # Extract the version of the built package
    - VERSION=$(python -c 'from importlib import metadata; print(metadata.version("sqlmodel"))')
    - echo "sqlmodel version $VERSION"
    # Ensure that version is not 0. (This conditional looks redundant, but YAML thinks
    # that [...] denotes a list.)
    - if [ "0" == "$VERSION" ]; then false; fi
  requires:
    - pip

about:
  home: https://github.com/tiangolo/sqlmodel
  summary: SQL databases in Python, designed for simplicity, compatibility, and robustness.
  doc_url: https://sqlmodel.tiangolo.com/
  license: MIT
  license_file: LICENSE
  description: |
    SQLModel is designed to simplify interacting with SQL databases in FastAPI
     applications, it was created by the same author. It combines SQLAlchemy
     and Pydantic and tries to simplify the code you write as much as possible,
     allowing you to reduce the code duplication to a minimum, but while getting
     the best developer experience possible. SQLModel is, in fact, a thin layer
     on top of Pydantic and SQLAlchemy, carefully designed to be compatible with
     both.

extra:
  recipe-maintainers:
    - tiangolo
    - maresb
    - thewchan
